version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.13
        environment:
          IMAGE_NAME: httpdumps
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            export TAG=`head -n 1 filename version.txt`
            docker build -t swarmiolabs/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push swarmiolabs/$IMAGE_NAME:$TAG
