
version: 2.1
jobs:
  build: 
      environment:
        IMAGE_NAME: httpdumps
      docker:
        - image: cimg/go:1.13
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build and push Docker image
            command: |
              export TAG=`head -n 1 version.txt`
              docker build -t swarmiolabs/$IMAGE_NAME:$TAG -t swarmiolabs/$IMAGE_NAME:latest .
              echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
              docker push swarmiolabs/$IMAGE_NAME
workflows:
  build-push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
